-- MySQL Script generated by MySQL Workbench
-- Fri Aug 14 17:59:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nutrition
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nutrition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nutrition` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nutrition` ;

-- -----------------------------------------------------
-- Table `nutrition`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`meals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`foods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`foods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `quantity` DECIMAL(5,2) NOT NULL DEFAULT 1,
  `unit` VARCHAR(15) NULL,
  `calories` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `proteins` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `carbohydrates` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `lipids` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `count` INT NOT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `brand_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_foods_brands1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_foods_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `nutrition`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`recipes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `calories` DECIMAL(6,2) NOT NULL,
  `proteins` DECIMAL(6,2) NOT NULL,
  `carbohydrates` DECIMAL(6,2) NOT NULL,
  `lipids` DECIMAL(6,2) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`diaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`diaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `quantity` DECIMAL(5,2) NOT NULL,
  `unit` VARCHAR(15) NULL,
  `date` DATE NOT NULL,
  `calories` DECIMAL(6,2) NOT NULL,
  `proteins` DECIMAL(6,2) NOT NULL,
  `carbohydrates` DECIMAL(6,2) NOT NULL,
  `lipids` DECIMAL(6,2) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `meal_id` INT NOT NULL,
  `brand_id` INT NULL,
  `food_id` INT NULL,
  `recipe_id` INT NULL,
  PRIMARY KEY (`id`, `meal_id`),
  INDEX `fk_journals_meals1_idx` (`meal_id` ASC),
  INDEX `fk_journals_brands1_idx` (`brand_id` ASC),
  INDEX `fk_diaries_recipes1_idx` (`recipe_id` ASC),
  INDEX `fk_diaries_foods1_idx` (`food_id` ASC),
  CONSTRAINT `fk_journals_meals1`
    FOREIGN KEY (`meal_id`)
    REFERENCES `nutrition`.`meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journals_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `nutrition`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diaries_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `nutrition`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diaries_foods1`
    FOREIGN KEY (`food_id`)
    REFERENCES `nutrition`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`calories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`calories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `calories` INT(5) NOT NULL,
  `proteins` INT(3) NOT NULL,
  `carbohydrates` INT(3) NOT NULL,
  `lipids` INT(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`goals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `calories` DECIMAL(6,1) NOT NULL,
  `proteins` DECIMAL(6,1) NOT NULL,
  `carbohydrates` DECIMAL(6,1) NOT NULL,
  `lipids` DECIMAL(6,1) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`food_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`food_recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` DECIMAL(5,2) NOT NULL,
  `calories` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `proteins` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `carbohydrates` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `lipids` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `food_id` INT NOT NULL,
  `recipe_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `food_id`, `recipe_id`),
  INDEX `fk_foods_has_recipes_recipes1_idx` (`recipe_id` ASC),
  INDEX `fk_foods_has_recipes_foods1_idx` (`food_id` ASC),
  CONSTRAINT `fk_foods_has_recipes_foods1`
    FOREIGN KEY (`food_id`)
    REFERENCES `nutrition`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_foods_has_recipes_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `nutrition`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutrition`.`weights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition`.`weights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `weight` DECIMAL(3,1) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
